/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BulkCreateEntriesRequest } from '../../models/bulk-create-entries-request';
import { BulkCreateEntriesResponse } from '../../models/bulk-create-entries-response';

export interface BulkCreate$Params {
      body: BulkCreateEntriesRequest
}

export function bulkCreate(http: HttpClient, rootUrl: string, params: BulkCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<BulkCreateEntriesResponse>> {
  const rb = new RequestBuilder(rootUrl, bulkCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BulkCreateEntriesResponse>;
    })
  );
}

bulkCreate.PATH = '/api/entries/bulk';
