/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EntryExportItem } from '../../models/entry-export-item';

export interface ExportEntries$Params {
}

export function exportEntries(http: HttpClient, rootUrl: string, params?: ExportEntries$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EntryExportItem>>> {
  const rb = new RequestBuilder(rootUrl, exportEntries.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<EntryExportItem>>;
    })
  );
}

exportEntries.PATH = '/api/entries/export';
