/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ImportEntriesRequest } from '../../models/import-entries-request';
import { ImportEntriesResponse } from '../../models/import-entries-response';

export interface ImportEntries$Params {
      body: ImportEntriesRequest
}

export function importEntries(http: HttpClient, rootUrl: string, params: ImportEntries$Params, context?: HttpContext): Observable<StrictHttpResponse<ImportEntriesResponse>> {
  const rb = new RequestBuilder(rootUrl, importEntries.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ImportEntriesResponse>;
    })
  );
}

importEntries.PATH = '/api/entries/import';
