/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EntryListResponse } from '../../models/entry-list-response';

export interface List$Params {
  q?: string;
  tags?: Array<string>;
  important?: boolean;
  visited?: boolean;
  addedFrom?: string;
  addedTo?: string;
  sort?: string;
  listId?: Array<string>;
  includeNsfw?: boolean;
  page?: number;
  pageSize?: number;
}

export function list(http: HttpClient, rootUrl: string, params?: List$Params, context?: HttpContext): Observable<StrictHttpResponse<EntryListResponse>> {
  const rb = new RequestBuilder(rootUrl, list.PATH, 'get');
  if (params) {
    rb.query('q', params.q, {});
    rb.query('tags', params.tags, {});
    rb.query('important', params.important, {});
    rb.query('visited', params.visited, {});
    rb.query('addedFrom', params.addedFrom, {});
    rb.query('addedTo', params.addedTo, {});
    rb.query('sort', params.sort, {});
    rb.query('listId', params.listId, {});
    rb.query('includeNsfw', params.includeNsfw, {});
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EntryListResponse>;
    })
  );
}

list.PATH = '/api/entries';
