/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListResponse } from '../../models/list-response';

export interface Lists$Params {
  id: string;
}

export function lists(http: HttpClient, rootUrl: string, params: Lists$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ListResponse>>> {
  const rb = new RequestBuilder(rootUrl, lists.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ListResponse>>;
    })
  );
}

lists.PATH = '/api/entries/{id}/lists';
