/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AttachmentResponse {
  downloadUrl?: string;
  id?: string;
  kind?: string;
  mimeType?: string;
  originalName?: string;
  sizeBytes?: number;
}
