/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ErrorItem } from '../models/error-item';
export interface BulkCreateEntriesResponse {
  createdCount?: number;
  errors?: Array<ErrorItem>;
  skippedCount?: number;
}
