/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BulkCreateEntriesRequest {
  items?: Array<{
    'title'?: string | null;
    'url'?: string | null;
  }>;
  urls?: Array<string>;
}
