/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EntryResponse {
  createdAt?: string;
  description?: string;
  detailedDescription?: string;
  id?: string;
  important?: boolean;
  manualThumbnailUrl?: string;
  tags?: Array<string>;
  thumbnailLargeUrl?: string;
  thumbnailUrl?: string;
  title?: string;
  updatedAt?: string;
  url?: string;
  visitedAt?: string;
  latestJobFailed?: boolean;
  aiSafe?: boolean;
  aiContext?: string;
}
