/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntryResponse } from '../models/entry-response';
export interface EntryListResponse {
  items?: Array<EntryResponse>;
  page?: number;
  pageSize?: number;
  totalCount?: number;
}
