/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EntryExportItem {
  addedAt?: string;
  description?: string;
  detailedDescription?: string;
  id?: string;
  lists?: Array<string>;
  tags?: Array<string>;
  thumbnailLargePath?: string;
  thumbnailPath?: string;
  title?: string;
  url?: string;
}
