/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AttachmentResponse } from '../models/attachment-response';
import { EntryResponse } from '../models/entry-response';
export interface EntryDetailsResponse {
  attachments?: Array<AttachmentResponse>;
  entry?: EntryResponse;
}
