/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntryExportItem } from '../models/entry-export-item';
export interface ImportEntriesRequest {
  items?: Array<EntryExportItem>;
  mode?: string;
}
