/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EntryResponse } from '../models/entry-response';
export interface Item {
  entry?: EntryResponse;
  reason?: string;
}
