/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface JobResponse {
  attempts?: number;
  createdAt?: string;
  entryId?: string;
  finishedAt?: string;
  id?: string;
  lastError?: string;
  lockedAt?: string;
  status?: string;
  type?: string;
}
