/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LlmRecommendRequest {
  customPrompt?: string;
  includeNsfw?: boolean;
  limit?: number;
  promptId?: string;
}
