/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PatchEntryRequest {
  description?: string;
  detailedDescription?: string;
  important?: boolean;
  tags?: Array<string>;
  title?: string;
}
