/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TagSuggestionResponse } from '../../models/tag-suggestion-response';

export interface Suggest$Params {
  prefix?: string;
  limit?: number;
}

export function suggest(http: HttpClient, rootUrl: string, params?: Suggest$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TagSuggestionResponse>>> {
  const rb = new RequestBuilder(rootUrl, suggest.PATH, 'get');
  if (params) {
    rb.query('prefix', params.prefix, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TagSuggestionResponse>>;
    })
  );
}

suggest.PATH = '/api/tags/suggest';
