license.name=Regnology PS Internal Tooling License 1.0
license.url=file://META/license/LICENSE
license.distribution=repo
license.comments=Proprietary - Regnology Group GmbH - All Rights Reserved - Internal Use Only
