/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LlmRecommendRequest } from '../../models/llm-recommend-request';
import { LlmRecommendResponse } from '../../models/llm-recommend-response';

export interface Llm$Params {
      body: LlmRecommendRequest
}

export function llm(http: HttpClient, rootUrl: string, params: Llm$Params, context?: HttpContext): Observable<StrictHttpResponse<LlmRecommendResponse>> {
  const rb = new RequestBuilder(rootUrl, llm.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LlmRecommendResponse>;
    })
  );
}

llm.PATH = '/api/recommendations/llm';
