/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EntryResponse } from '../../models/entry-response';

export interface Random$Params {
  limit?: number;
  includeNsfw?: boolean;
}

export function random(http: HttpClient, rootUrl: string, params?: Random$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EntryResponse>>> {
  const rb = new RequestBuilder(rootUrl, random.PATH, 'get');
  if (params) {
    rb.query('limit', params.limit, {});
    rb.query('includeNsfw', params.includeNsfw, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<EntryResponse>>;
    })
  );
}

random.PATH = '/api/recommendations/random';
